const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Anchor,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.Browser.Acts.Vibrate,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.LoadState,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Acts.SetX
	];
};
self.C3_JsPropNameTable = [
	{ТвердеТіло: 0},
	{Спрайт: 0},
	{Якір: 0},
	{Стеження: 0},
	{Спрайт2: 0},
	{Спрайт3: 0},
	{Спрайт4: 0},
	{Платформер: 0},
	{Спрайт5: 0},
	{Дотик: 0},
	{Спрайт6: 0},
	{Текст: 0},
	{Браузер: 0},
	{ЛокальнеСховище: 0},
	{Спрайт8: 0},
	{Спрайт7: 0},
	{Спрайт9: 0},
	{полеДляГри: 0},
	{Спрайт11: 0},
	{Спрайт12: 0},
	{полеДляСмерті: 0},
	{Текст2: 0}
];

self.InstanceType = {
	Спрайт: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Дотик: class extends self.IInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	Браузер: class extends self.IInstance {},
	ЛокальнеСховище: class extends self.IInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	полеДляГри: class extends self.ISpriteInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	полеДляСмерті: class extends self.ISpriteInstance {},
	Текст2: class extends self.ITextInstance {}
}